### ISSUE TITLE
Unable to Download Dataset from Provided Link

### ISSUE THREAD

**Issue by mrclovvn** [IIT-PAVIS/SC3K#1]
Hi,

Thank you for sharing the code of your valuable work. I'm interested in building upon your research, but I've encountered an issue accessing the dataset. The download link seems to be unresponsive, continually showing "Checking link". Could you please verify the link's functionality or suggest an alternative method for downloading the dataset? Your assistance would greatly facilitate my ongoing research.

Thank you for your time and consideration.

Best regards,

Shawn

**Comment by zohaibmohammad** [comment]
Hi,

Thank you for reporting the error. The link has been updated.
We used the KeypointNet dataset (https://github.com/qq456cvb/KeypointNet).

Kind regards,
Mohammad

**Comment by mrclovvn** [comment]
Thanks a lot for your response! I have a follow-up question regarding the calculation of the `Inclusivity` metric, specifically about the predefined threshold $\tau_2$ mentioned in equation 10 of your paper. In the paper's text, it's stated that the value is set to 0.1, as mentioned in the caption of Table 1. However, in the code provided at [SC3K/test.py#L40](https://github.com/IIT-PAVIS/SC3K/blob/ab4c5d1f981e1c436c2865efaf4086975fc9fdbd/test.py#L40), the threshold is set to 0.05. Could you please clarify which setting was actually used in your experiments? Or is there a particular reason for this discrepancy that I might have overlooked? I want to ensure I correctly understand and implement this metric in my work.

Thank you in advance for your time and clarification.

**Comment by zohaibmohammad** [comment]
The `Inclusivity` metric is taken from the [Unsupervised Learning of Category-Specific
Symmetric 3D Keypoints from Point Sets](https://arxiv.org/pdf/2003.07619.pdf). We used it to evaluate *SC3K* for different thresholds ($\tau_2$) as described in the supplementary document. You can select any threshold considering your keypoints and keep it the same for the baseline methods for fare comparison.
